# Generated by Django 2.1.4 on 2018-12-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='secret_identity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='characters.Character'),
        ),
        migrations.AlterField(
            model_name='sidekick',
            name='secret_identity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidekick', to='characters.Character'),
        ),
    ]
